# Generated by Django 4.2.16 on 2024-12-01 11:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Book subtitle or tagline', max_length=200, null=True)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='book_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the store', max_length=200)),
                ('website', models.URLField(blank=True, help_text="Store's website URL", null=True)),
                ('logo', models.ImageField(blank=True, help_text='Store logo image', null=True, upload_to='store_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('excerpt', models.TextField(default='Preview coming soon...', editable=False, help_text='A short preview of the work')),
                ('category', models.CharField(choices=[('POEM', 'Poem'), ('SHORT_STORY', 'Short Story'), ('ESSAY', 'Essay')], default='ESSAY', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='works/')),
                ('reading_time', models.PositiveIntegerField(blank=True, help_text='Estimated reading time in minutes', null=True)),
                ('publication_date', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_url', models.URLField(help_text='URL where the book can be purchased from this store')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Price in this specific store (if different from book's base price)", max_digits=6, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the book is currently available in this store')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.store')),
            ],
            options={
                'verbose_name': 'Book Store Link',
                'verbose_name_plural': 'Book Store Links',
                'unique_together': {('book', 'store')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='stores',
            field=models.ManyToManyField(related_name='books', through='api.BookStore', to='api.store'),
        ),
    ]
